version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    networks:
      - teste
    volumes:
      - .:/var/www
    ports:
      - 8000:80
      - 8080:8080
    environment:
      - PHP_FPM_USER=www-data
      - PHP_FPM_GROUP=www-data

networks:
  teste:
    external: true
